### ISSUE TITLE
Awesome!!!

### ISSUE THREAD

**Issue by benmliang** [wingrunr21/flat-ui-sass#1]
it's so awesome to see there is sass version of flat ui, I probably wanna use it on my angularJS project. Good job!

Do you have a plan for vanilla SASS or compass version ?

**Comment by wingrunr21** [comment]
Yep, they are listed in the README. :smiley: 

The skeleton for those two is there already. Tomorrow I'm aiming on finishing Compass integration, vanilla SASS, and possibly investigate bower.

**Comment by benmliang** [comment]
that's Awesome. Wait for you :D

**Comment by designmodo** [comment]
We'll check your project very soon :+1:

**Comment by benmliang** [comment]
Could you tell me when you can finish vanilla SASS or SCSS?

**Comment by wingrunr21** [comment]
No ETA

**Comment by wingrunr21** [comment]
@benmliang go ahead and watch these two issues: #2 and #3
