### ISSUE TITLE
Support Sass v3.2

### ISSUE THREAD

**Issue by wingrunr21** [wingrunr21/flat-ui-sass#15]
As of commit [0fcdff8](https://github.com/rails/sass-rails/commit/0fcdff806511d0cfaf0bf379f3530ad11cb16f5c), `sass-rails` now explicitly precludes Sass v3.3+ from installation. This is a blocker for those attempting to use this gem along with the latest versions of Rails.

Two areas need modified in order to relax the Sass requirement:
- The [asset helper function](https://github.com/wingrunr21/flat-ui-sass/blob/master/vendor/assets/stylesheets/flat-ui/_variables.scss#L4) needs to be reverted to the method used by [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/vendor/assets/stylesheets/bootstrap/_variables.scss#L4)
- The `interpolate_variable` function will need to be modified to support Sass 3.2. This will affect the [`calc-color`](https://github.com/wingrunr21/flat-ui-sass/blob/master/vendor/assets/stylesheets/flat-ui/_mixins.scss#L554) mixin and subsequently the [palette module](https://github.com/wingrunr21/flat-ui-sass/blob/master/vendor/assets/stylesheets/flat-ui/modules/_palette.scss).

**Comment by akshatpradhan** [comment]
Just a heads up, we're currently using the 3.2. branch and its been deployed to production. https://github.com/akshatpradhan/compliance_chimp/blob/master/Gemfile#L12

**Comment by wingrunr21** [comment]
Awesome thanks. I will need to test against Flat UI free then I will merge into master.

FYI you realize you have Flat UI Pro checked into and available from a public repo right? Not sure Designmodo will appreciate that.

**Comment by akshatpradhan** [comment]
yeah I have my own set off issues with him and I can't wait to move away from Flat UI the first chance I get. He's antithetical to the very notion of community and his licensing is absurd: https://github.com/designmodo/Flat-UI/issues/124

We noted that in our commit and we've specifically pointed to the PR that verifies we own a developers licenses to Flat UI Pro: https://github.com/akshatpradhan/compliance_chimp/pull/61

The Highcharts licensing methodology IS the best way to license Flat UI (and make money) but he won't read up on it.

**Comment by wingrunr21** [comment]
I will test Flat UI Free later today and hopefully merge 3.2 support into master later tonight.
