### ISSUE TITLE
Compatible with Rails 3.2?

### ISSUE THREAD

**Issue by akshatpradhan** [wingrunr21/flat-ui-sass#16]
Is this compatible with Rails 3.2?

**Comment by wingrunr21** [comment]
Yes why

**Comment by akshatpradhan** [comment]
@wingrunr21 Because we're currently working on using this gem to get Flat UI Pro working, and we get an error saying it requires sass >= 3.3

https://github.com/akshatpradhan/compliance_chimp/issues/22

**Comment by wingrunr21** [comment]
See #14

**Comment by akshatpradhan** [comment]
@wingrunr21 I'm asking this question because of #14 actually.  #14 makes it sound like this gem is only compatible with sass 3.2 but we're getting errors saying we're required to have sass 3.3 . I guess I'm lost completely. Does this gem work with sass 3.2? If so, why are we getting an error requiring us to have 3.3?

**Comment by wingrunr21** [comment]
I implemented sass 3.2 support in a branch yesterday. #14 introduced the problem and #15 is tracking it. I need a few testers before I merge support.

**Comment by akshatpradhan** [comment]
@wingrunr21 We're here! What would you like us to test?

**Comment by akshatpradhan** [comment]
I think @adamico will check out your 3.2 support branch we'll paste some logs showing brokenness, that might be of help for starters.

**Comment by wingrunr21** [comment]
Ok, since this is the same issue as #15, I am going to close this issue. Let's move the discussion into there.
