### ISSUE TITLE
Error when converting to flat-ui-pro

### ISSUE THREAD

**Issue by nouira** [wingrunr21/flat-ui-sass#19]
I'm having an error when i run fui_convert

  Converting LESS files to Scss:
  spaces.less
  Reading shared mixins from mixins.less
Uncaught exception: undefined method `get_paths_by_type' for #<Converter:0x0000000222e1b8>
    /home/zied/.rvm/gems/ruby-2.0.0-p195/gems/bootstrap-sass-3.1.1.1/tasks/converter/less_conversion.rb:141:in`bootstrap_less_files'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/gems/bootstrap-sass-3.1.1.1/tasks/converter/less_conversion.rb:48:in `load_shared'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/gems/bootstrap-sass-3.1.1.1/tasks/converter/less_conversion.rb:39:in`convert_less'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/lib/tasks/converter/flat_ui_less_conversion.rb:31:in `block in process_flat_ui_stylesheet_assets!'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/lib/tasks/converter/flat_ui_less_conversion.rb:26:in`each'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/lib/tasks/converter/flat_ui_less_conversion.rb:26:in `process_flat_ui_stylesheet_assets!'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/lib/tasks/converter.rb:71:in`process_flat_ui!'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/lib/flat-ui-sass/cli.rb:10:in `start'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bundler/gems/flat-ui-sass-cd8604a9c863/bin/fui_convert:9:in`<top (required)>'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bin/fui_convert:23:in `load'
    /home/zied/.rvm/gems/ruby-2.0.0-p195/bin/fui_convert:23:in`<top (required)>'

**Comment by Swolie** [comment]
+1

**Comment by wingrunr21** [comment]
Taking a look now. Should be able to get it fixed today.

**Comment by itschn** [comment]
1+

**Comment by wingrunr21** [comment]
@itschn are you having this issue? What version of Flat UI? I pushed a fix for this awhile ago.

**Comment by itschn** [comment]
@wingrunr21 Flat-UI-Pro-v1.3.1

**Comment by wingrunr21** [comment]
See #26

**Comment by itschn** [comment]
thnx
