### ISSUE TITLE
Add bower support

### ISSUE THREAD

**Issue by wingrunr21** [wingrunr21/flat-ui-sass#21]
Self-explanatory

**Comment by rpocklin** [comment]
+1 - will you accept a PR?

BTW `bower install flat-ui` is old and `bower install flat-ui-official` is the **lesser** version.

**Comment by wingrunr21** [comment]
I will definitely accept a PR!

I don't maintain `flat-ui` or `flat-ui-official`, only the sass port. You'll want to file an issue over in [designmodo/Flat-UI](https://github.com/designmodo/Flat-UI)

**Comment by wingrunr21** [comment]
Resolved via #33
