### ISSUE TITLE
gem install flat-ui-sass: could not find a valid gem

### ISSUE THREAD

**Issue by fiznool** [wingrunr21/flat-ui-sass#22]
When running `gem install flat-ui-sass` I get:

```
ERROR:  Could not find a valid gem 'flat-ui-sass' (>= 0) in any repository
```

**Comment by wingrunr21** [comment]
yes because it isn't published on rubygems

**Comment by fiznool** [comment]
OK, well I was just following the instructions here: https://github.com/wingrunr21/flat-ui-sass#vanilla-sass-no-compass-or-rails

**Comment by neagle** [comment]
Those instructions confused me, too. But I was able to [find instructions](http://stackoverflow.com/questions/2577346/how-to-install-gem-from-github-source) on how to install the gem after cloning the project from Github, and it worked fine.

```
$ git clone https://github.com/wingrunr21/flat-ui-sass.git && cd flat-ui-sass
$ gem build flat-ui-sass.gemspec
$ [sudo] gem install flat-ui-sass-2.1.3.gem
```

**Comment by wingrunr21** [comment]
You guys should really be using Bundler as opposed to installing the gem itself. I'll aim to get my remaining tasks done this week and push the first version up to rubygems.

**Comment by neagle** [comment]
Is there an advantage to using the Bundler when I just need a one-time use of the `fui_convert` command? In my case, I'm just stripping apart the converted assets and putting them in the appropriate place in my Gulp-powered build. (Which, I might note, is working great, though I had to do a bit of extra work to incorporate Bourbon to get some of the needed color functions.)
