### ISSUE TITLE
Don't stomp on bootstrap's $icon-font-* variables

### ISSUE THREAD

**Issue by wingrunr21** [wingrunr21/flat-ui-sass#24]
Right now the auto conversion will redefine `$icon-font-path`, `$icon-font-name`, and `$icon-font-svg-id`. We should not do that.

[Flat UI variable](https://github.com/wingrunr21/flat-ui-sass/blob/master/vendor/assets/stylesheets/flat-ui/_variables.scss#L113)
[Bootstrap Variable](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L83)

**Comment by reyesyang** [comment]
Fix in PR #43 to branch 2-2-support
