### ISSUE TITLE
remove compass dependencies 

### ISSUE THREAD

**Issue by gad2103** [wingrunr21/flat-ui-sass#25]
hi there. thanks for making this. i'm trying to only use the sass stuff from this project in another project. i keep getting errors when i import the 'variables' file like so:

```
Syntax error: $color: "tint(#34495e, 91%)" is not a color for `adjust-hue'
        on line 268 of /Users/gabrielduncan/Sites/yo-ff-app/client/bower_components/flat-ui/sass/_variables.scss
```

i'm assuming that's because i'm using grunt-sass to compile and it probably doesn't know what to do with tint. 

do you have any suggestions on how to fix this?

**Comment by gad2103** [comment]
ok. so i got this working by including this gist in the variables file: 
https://gist.github.com/benfrain/7545629

now its working!

**Comment by wingrunr21** [comment]
`tint` is provided by this gem [here](https://github.com/wingrunr21/flat-ui-sass/blob/master/lib/flat-ui-sass/sass_functions.rb#L32). There must be something with your setup that is not loading the gem into the environment correctly. Can you describe your workflow?

**Comment by gad2103** [comment]
yeah. that's it. i'm using the yeoman angular fullstack generator which uses grunt-sass-contrib. it isn't currently set up to load a config.rb file. it just uses sass and looks for files in the bower_components directory to compile. so i just pulled the sass stuff out of your repo and put it in bower_components and added the missing functions to a file that gets imported into the variables file. 

it would be great if there was a bower version of this! i suppose i could fork and do a PR...

anyway, this repo was very helpful. thanks again.

**Comment by wingrunr21** [comment]
#21 is for bower support.
