### ISSUE TITLE
why can not flat-ui icon show?

### ISSUE THREAD

**Issue by myhat123** [wingrunr21/flat-ui-sass#27]
<h2><i class="fui-plus"></i>test</h2>

it does not work.

how to?

**Comment by wingrunr21** [comment]
I need more information than this to troubleshoot.

This SASS file loads the icon font and sets up the utility classes:
https://github.com/wingrunr21/flat-ui-sass/blob/master/vendor/assets/stylesheets/flat-ui/modules/_glyphicons.scss
