### ISSUE TITLE
Update converter for Flat UI Pro v1.3.1

### ISSUE THREAD

**Issue by benjaminathlan** [wingrunr21/flat-ui-sass#31]
Hey, I've tried to convert the latest version I've just bought but got this message : 

```
tasks/converter.rb:78:in `initialize': No such file or directory @ rb_sysopen - vendor/assets/stylesheets/flat-ui-pro/mixins/_alerts.scss (Errno::ENOENT)
```

Could you please help ?

**Comment by wingrunr21** [comment]
The converter hasn't been updated to support v1.3. This is covered by #26.
