### ISSUE TITLE
Rails 4.1.6 & Ruby 2.1.3 assets initialization error

### ISSUE THREAD

**Issue by cseydel** [wingrunr21/flat-ui-sass#35]
Hi,
I just want to try out FlatUI rails for the first time with rails 4.1.6 and ruby 2.1.3 and suffering from an assets error:

`
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( flat-ui/tile/ribbon.png )` to `config/initializers/assets.rb` and restart your server
`

I added this line, restarted but still this error is occurring. Have you any advise to get it working?

Best,
Christoph

**Comment by yujingz** [comment]
For now what you can do is 

``` ruby
Rails.application.config.assets.precompile += ['flat-ui/**/*']
```

**Comment by cseydel** [comment]
worked, thanks.
