### ISSUE TITLE
uninitialized constant Converter::LessConversion (NameError) when running fui_convert

### ISSUE THREAD

**Issue by tsaifi9** [wingrunr21/flat-ui-sass#36]
on branch '2-2-support'

Gemfile:
gem 'rails', '4.2.0'
gem 'sass-rails', '4.0.0'
gem 'jquery-rails'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'flat-ui-sass', github: 'wingrunr21/flat-ui-sass', branch: "2-2-support"

Error:
$ bundle exec fui_convert
/home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/tasks/converter/flat_ui_less_conversion.rb:3:in `<module:FlatUILessConversion>': uninitialized constant Converter::LessConversion (NameError)
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/tasks/converter/flat_ui_less_conversion.rb:2:in`class:Converter'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/tasks/converter/flat_ui_less_conversion.rb:1:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/tasks/converter.rb:23:in`require_relative'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/tasks/converter.rb:23:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/flat-ui-sass/cli.rb:2:in`require'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/lib/flat-ui-sass/cli.rb:2:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/bin/fui_convert:8:in`require'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bundler/gems/flat-ui-sass-de76108f0934/bin/fui_convert:8:in `<top (required)>'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bin/fui_convert:23:in`load'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bin/fui_convert:23:in `<main>'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bin/ruby_executable_hooks:15:in`eval'
    from /home/user/.rvm/gems/ruby-2.2.0@rezgem/bin/ruby_executable_hooks:15:in `<main>'

**Comment by wingrunr21** [comment]
Thanks for the bug report.

I'm aware of this. The 2.2 support isn't done yet.
