### ISSUE TITLE
Flat-UI-Pro-Icons font-family not using compiled assets (2-2-support branch)

### ISSUE THREAD

**Issue by jordigg** [wingrunr21/flat-ui-sass#37]
I'm trying out the 2-2-support branch and the Flat-UI-Pro-Icons don't use the compiled assets on production. If I change the font to Glyphicons Halflings works fine.

When I check the compiled css shows the font trying to find the assets without being compiled so it can't be found on production:

``` css
@font-face{font-family:'Flat-UI-Pro-Icons'; src:url("flat-ui-pro/glyphicons/flat-ui-pro-icons-regular.eot");
```

I have checked and the flat-ui-pro-icons-regular.eot and the other are being compiled just fine. Does anyone know how I can fix this?

Thanks!

**Comment by wingrunr21** [comment]
Looks like the URL path is wrong. I had to tweak that in the converter. Let me take a look.

**Comment by jordigg** [comment]
I'm using rails 4.1.8, I was updating an older version of Flat-UI-Pro to the latest one on 2-2-support.

I'm importing the css this way:

``` css
@import 'bootstrap-sprockets';
@import 'flat-ui-pro/variables';
@import 'bootstrap';
@import 'flat-ui-pro';
```

Do you think I'm missing something? Works fine on development, it doesn't on production.

**Comment by wingrunr21** [comment]
I just pushed a commit up. Pull that down and give it a try.

**Comment by jordigg** [comment]
Still nothing. That's the error I get.

```
assets/flat-ui-pro/glyphicons/flat-ui-pro-icons-regular.woff 404 (Not Found)
```

The files are compiled but the css doesn't point to the compiled one (flat-ui-pro-icons-regular-098b9551d21ff2a1711c37c0af64b811.ttf), it points the standard one (flat-ui-pro-icons-regular.ttf).

Maybe I did something wrong during the update. I'm having this issue with the carets on the breadcrumbs. Is there anyone else having problems with it?

I'll change the flat-ui-pro-icons for the Glyphicons Halflings until I find a solution.

**Comment by wingrunr21** [comment]
You need to add the import for flat-ui-sprockets before flat-ui-pro:

```
@import 'flat-ui-sprockets';
@import 'flat-ui-pro';
```

This is new for this version as it solves a few problems.

**Comment by jordigg** [comment]
I have it already, check my first messages.

``` scss
@import 'bootstrap-sprockets';
@import 'flat-ui-pro/variables';
@import 'bootstrap';
@import 'flat-ui-pro';
```

**Comment by wingrunr21** [comment]
No you don't. `bootstrap-sprockets` is not the same.

**Comment by jordigg** [comment]
My fault! will try now. Didn't know that this one existed, haven't seen it on the readme.

**Comment by wingrunr21** [comment]
The README isn't updated yet. You are using an unstable branch.

**Comment by jordigg** [comment]
It worked! :clap: Thanks so much @wingrunr21 really appreciate your help and work!

**Comment by wingrunr21** [comment]
:+1:
