### ISSUE TITLE
Sass Compilation Failed!: unbound variable $flat-ui-sass-asset-helper

### ISSUE THREAD

**Issue by fareez-ahamed** [wingrunr21/flat-ui-sass#38]
I get this error when using Gulp sass to compile flat-ui-sass. I'm using laravel-elixir which inturn uses gulp sass internally to compile

Am I missing something here?

**Comment by wingrunr21** [comment]
I haven't tested this against `node-sass` so that is possibly the problem. Are you using master or `2-2-support`?

**Comment by fareez-ahamed** [comment]
I used Bower to pull it... ~2.1.3 is the version according to by bower.json

**Comment by fareez-ahamed** [comment]
This is due to fact that I missed to explicitly import variables file, but I get different error in node sass, which I will open as a separate issue... Closing this...

**Comment by q2amarket** [comment]
I am having the same issue. I am using. Any resolution to this error? I have install the gem so I have no idea which branch it is loading.

**Comment by wingrunr21** [comment]
Which issue? This issue was due to an error made by the user.

**Comment by 0xycvv** [comment]
rake aborted!
Sass::SyntaxError: Undefined variable: "$flat-ui-sass-asset-helper".
Sass::SyntaxError: Undefined variable: "$brand-primary".

I am using `2-2-support` and I follow the instruction

```
@import 'bootstrap-sprockets';
@import 'flat-ui-sprockets';
@import 'flat-ui/variables';
@import 'bootstrap';
@import 'flat-ui';
```

How to get rid of it?

**Comment by smshin7** [comment]
I am also having this issue during a bundle exec rake assets:precompile

Sass::SyntaxError: Undefined variable: "$brand-primary".

**Comment by ferrisoxide** [comment]
Also had the issue with `$flat-ui-sass-asset-helper` not bound when using Compass and flat-ui-sass in a Jekyll project. 

Was a matter of uncommenting the line in `_variables.scss` that defines the variable. Hope that helps somebody.
