### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$btn-default-bg".

### ISSUE THREAD

**Issue by metaskills** [wingrunr21/flat-ui-sass#9]
This seems to be a bug with flat-ui-pro (have not yet checked free) but the conversion of  `variables.less` seems to be broken. In the source file.

``` less
// Spinner
// -------------------------

@spinner-input-width:           55px;
@spinner-input-font-size:       ceil(@component-font-size-base * 1.333); // ~20px
@spinner-input-line-height:     1.3; // ~26px
// ...
```

And in the converted `_variables.scss` file I see.

``` scss
// Spinner
// -------------------------

$adjust-huener-input-width:             55px !default;
$adjust-huener-input-font-size:         ceil($component-font-size-base * 1.333) !default; // ~20px
$adjust-huener-input-line-height:       1.3 !default; // ~26px
// more bad names...
```

**Comment by metaskills** [comment]
I should point out that I was not able to bundle the gem with my project since the latest sass uses an old version of the listen gem. I commented on their issues about that already. The way I converted my pro folder was to place it at the root of this project and run:

``` ruby
require_relative 'lib/tasks/converter'
Converter.new(:pro, './flat-ui-pro').process_flat_ui!
```

**Comment by wingrunr21** [comment]
I haven't checked the conversion on Flat UI Pro 1.2.4 yet. It works as expected in 1.2.3. Let me see.

As for SASS, I need variable introspection to convert one of the Flat UI Free modules (which isn't in Pro) thus the requirement on SASS v3.3. The Pro conversion doesn't actually require it but I am version tracking Free since I am vendoring it.

**Comment by wingrunr21** [comment]
The bug is in `bootstrap-sass`. Patch forthcoming.

**Comment by metaskills** [comment]
Thanks Stafford... was trying to figure it out myself...

**Comment by wingrunr21** [comment]
want me to not patch it? :smile:

**Comment by metaskills** [comment]
Oh, please patch it. I have not made my way to solving the issue yet. BTW, here was the Sass issue I spoke of. Great news on that front. https://github.com/nex3/sass/issues/955#issuecomment-33433238

**Comment by wingrunr21** [comment]
Should be fixed now. Flat-UI Pro and Free were both affected.

**Comment by metaskills** [comment]
THANKS! Will try it out again later tonight.
